export VEYRA_NAME="Veyra Linux"
export VEYRA_VERSION="0.1.0"
export VEYRA_CODENAME="Genesis"
export VEYRA_API="https://veyra-api.abdualialderson.workers.dev/"
export VEYRA_REPOSITORY="https://raw.githubusercontent.com/abduali-sec/veyra-repo/main"
export VEYRA_SOURCE="https://github.com/abduali-sec/veyralinux"
