VEYRA_LOGO=/usr/share/veyra/branding/logo
VEYRA_ICONS=/usr/share/veyra/branding/icons
VEYRA_WALLPAPERS=/usr/share/veyra/branding/wallpapers
VEYRA_FASTFETCH=/usr/share/veyra/branding/fastfetch
VEYRA_SDDM=/usr/share/veyra/branding/sddm
