VEYRA_NAME="Veyra Linux"
VEYRA_VERSION="0.1.0"
VEYRA_CODENAME="Genesis"
VEYRA_PACKAGE_MANAGER="vpm"
VEYRA_REPOSITORY="Veyra Repository"
VEYRA_API="https://veyra-api.abdualialderson.workers.dev/"
VEYRA_SUPPORT="https://t.me/Veyralinuxx"
VEYRA_PROJECT="https://github.com/abduali-sec/veyralinux"
VEYRA_MADE="Made in Abduali"
