[repository]
name=Veyra Repository
url=https://raw.githubusercontent.com/abduali-sec/veyra-repo/main

[api]
name=Veyra API
url=https://veyra-api.abdualialderson.workers.dev/

[package-manager]
name=vpm
