NAME=Veyra Linux
VERSION=0.1.0
CODENAME=Genesis
PACKAGE_MANAGER=vpm
API=https://veyra-api.abdualialderson.workers.dev/
REPOSITORY=https://raw.githubusercontent.com/abduali-sec/veyra-repo/main
PROJECT=https://github.com/abduali-sec/veyralinux
SUPPORT=https://t.me/Veyralinuxx
MADE_IN=Abduali
