title    Veyra Linux Live — Accessibility (%ARCH%, UEFI)
linux    /veyra/boot/x86_64/vmlinuz-linux
initrd   /veyra/boot/x86_64/initramfs-linux.img
options  archisobasedir=veyra archisosearchfilename=/veyra/boot/x86_64/vmlinuz-linux accessibility=on
