[Veyra]
Browser=firefox.desktop
FileManager=org.kde.dolphin.desktop
Terminal=org.kde.konsole.desktop
Editor=org.kde.kate.desktop
ArchiveManager=org.kde.ark.desktop
ImageViewer=org.kde.gwenview.desktop
SystemSettings=systemsettings
ControlCenter=veyra-center
PackageManager=vpm
Installer=veyra-installer
Doctor=veyra-doctor
Welcome=veyra-welcome
